### ISSUE TITLE
Problems with shuffle

### ISSUE THREAD

**Issue by TigerAB1** [Antonious-Grigis/Shuffled-Model-of-Differential-Privacy-in-Federated-Learning#2]
hi,I appreciate your contribution to this project.But while looking at the code, I don't understand what step of the shuffle process is reflected?
![image](https://github.com/Antonious-Grigis/Shuffled-Model-of-Differential-Privacy-in-Federated-Learning/assets/116572728/7c26a6d0-e6cf-4041-a35d-0b9e3bc6a1d0)

**Comment by Antonious-Grigis** [comment]
This step appears in the privacy computation. There are different ways to compute the privacy of the shuffled model:
1) using the subsampled shuffling and then using the strong composition theorem as in this paper.
2) using RDP analysis of the subsampled shuffled model as in the following papers

[On the renyi differential privacy of the shuffle model](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Oi7ZTFEAAAAJ&citation_for_view=Oi7ZTFEAAAAJ:4TOpqqG69KYC)
AM Girgis, D Data, S Diggavi, AT Suresh, P Kairouz
Proceedings of the 2021 ACM SIGSAC Conference on Computer and Communications

[Renyi Differential Privacy of the Subsampled Shuffle Model in Distributed Learning](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Oi7ZTFEAAAAJ&cstart=20&pagesize=80&citation_for_view=Oi7ZTFEAAAAJ:Tyk-4Ss8FVUC)
AM Girgis, D Data, S Diggavi
Advances in Neural Information Processing Systems (NeurIPS 2021)
